# Generated by Django 5.0 on 2023-12-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_tag_order_customer_order_product_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='demoapp.tag'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Out of delivery', 'Out of delivery'), ('Delivery', 'Delivery')], max_length=200, null=True),
        ),
    ]
